name: "Publish package"

on:
  push:
    tags:
      - '*.*.*'

jobs:
  pack:
    name: Build package
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Authenticate with NPM
        run: npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: |
          npm publish --access public
